# Generated by Django 5.0 on 2023-12-16 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rolesmodel_alter_filesmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 2, 29, 0, 315613)),
        ),
        migrations.AlterField(
            model_name='rolesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 2, 29, 0, 316055)),
        ),
    ]
