# Generated by Django 5.0 on 2023-12-16 20:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_filesmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 2, 39, 44, 457240)),
        ),
        migrations.AlterField(
            model_name='rolesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 2, 39, 44, 457707)),
        ),
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 12, 17, 2, 39, 44, 458044))),
                ('roles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.rolesmodel')),
            ],
        ),
    ]
